import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./Components/Navber";
import Footer from "./Components/Footer";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navber />
        <main className="md:w-6xl mx-auto">{children}</main>
        <Toaster
          richColors
          position="top-center"
          toastOptions={{
            duration: 1000,
            style: { fontSize: "14px", borderRadius: "12px" },
          }}
        />
        <Footer />
      </body>
    </html>
  );
}
